### ISSUE TITLE
Care Ended Patients Not Searchable

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#1]
Hi @darkirui 
When a patient is care ended in v1.7, they are not found in search results.
This is obviously a bug since the records should be viewable and the client may need to be reactivated.

Do you have time to look into this?

**Comment by darkirui** [comment]
@chris-githu let me look into it tomorrow. Thanks.

**Comment by darkirui** [comment]
Fixed. Fix will be available in the next build.
