### ISSUE TITLE
Lab Form Missing Users

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#13]
Lab form for migrated facilities not picking all users on the Ordered by and Reported by Fields.

**Comment by chris-githu** [comment]
@vogoti 
Please run these scripts to resolve this issue
[vw_UserList.txt](https://github.com/chap-uzima/IQCare/files/2980550/vw_UserList.txt)
[mst_Employee.txt](https://github.com/chap-uzima/IQCare/files/2980551/mst_Employee.txt)

**Comment by chris-githu** [comment]
@vogoti Is this now resolved?

**Comment by vogoti** [comment]
@chris-githu I have run the scripts against Kikuyu and Kiserian DBs but the issue has not been resolved

**Comment by chris-githu** [comment]
@vogoti 
Please confirm whether cache was refreshed.

**Comment by vogoti** [comment]
@chris-githu this works after refreshing the cache,thanks
