### ISSUE TITLE
Delete Batch during Drugs Received delete

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#16]
Delete Batch during `Drugs Received` delete if no other transactions rely on it

**Comment by Muchina-David** [comment]
@mkaburu We noticed something yesterday about deleting transactions. You can explain it better.

**Comment by chris-githu** [comment]
@mkaburu Please confirm and close if this is resolved.
@vogoti I'll send you over email scripts to run at Kiserian to apply this fix.
421 will handle new deployments

**Comment by mkaburu** [comment]
Done
