### ISSUE TITLE
Date Format in Pharmacy Module

### ISSUE THREAD

**Issue by Muchina-David** [chap-uzima/IQCare#18]
@chris-githu requesting if the date format for Date pickers in Pharmacy module can  be set to pick D/M/Y. Its currently picking M/D/Y.
![image](https://user-images.githubusercontent.com/48719634/54607886-89291e80-4a60-11e9-98d2-864c225677ab.png)

**Comment by chris-githu** [comment]
@mkaburu @Muchina-David 
Please test this and confirm
