### ISSUE TITLE
Real-time stock data in system 

### ISSUE THREAD

**Issue by Muchina-David** [chap-uzima/IQCare#21]
@chris-githu @irenefaith We noted yesterday that we cannot view stocks in the system from the front end. After adding all the drugs, we could not tell how much we have or whether what we have added has reflected in the total stocks. This is important for knowing how much we have in the main store and dispensing store store. I suggest having a "View stocks" tab below Adjust stocks on the right hand side. I know there is a dashboard under development but that can be graphical etc. For the "View stocks" it can be a simple table of all drugs with their quantities.

![image](https://user-images.githubusercontent.com/48719634/54664190-9b549c80-4af4-11e9-98d0-c5dcf265f46a.png)

The table below explains what i mean (something of the sort):

![image](https://user-images.githubusercontent.com/48719634/54665312-cbea0580-4af7-11e9-860c-d49af6acc3d2.png)

**Comment by chris-githu** [comment]
@Muchina-David 
Can we call this (or implement it as) a `Stock Summary` or is that a different report?

**Comment by Muchina-David** [comment]
@chris-githu Yes, we can call it Stock Summary. Not really a report, just view-able data, but maybe one can be able to extract as Excel (if possible).

**Comment by chris-githu** [comment]
@Muchina-David 
Will this do?

<img width="1230" alt="Screen Shot 2019-03-22 at 4 52 20 PM" src="https://user-images.githubusercontent.com/13725334/54827550-5599fe80-4cc3-11e9-982c-e31ac8874e46.png">

**Comment by Muchina-David** [comment]
@chris-githu Yes. Something like that. I have a few suggestions; 

1. For the pack sizes, since they will be the same for a particular batch, can they appear just once in a column after batch number?
2. For the packs/ bottles descriptions, what if at the title for Quantity we put Quantity (packs/ bottles) and then not have the descriptions against each number?  
3. In the last column please replace 'at' with 'on' to read Stock on Hand.
4. Is it possible to make the data for main store and dispensing store visually distinct for the user? 

By the way, what i had given was just to show the info required. If you have a better way of capturing the data please do so. I believe you understand layout better than i do.

**Comment by chris-githu** [comment]
@Muchina-David 
Please test this and confirm

**Comment by Muchina-David** [comment]
@chris-githu I think it's good and all the suggestions have been captured. I have tested Receiving and Issuing transactions as well as dispensing, and all are updating in the Stock Summary. Thanks.
