### ISSUE TITLE
Receiving/ Issuing drugs recent transactions summary 

### ISSUE THREAD

**Issue by Muchina-David** [chap-uzima/IQCare#22]
@chris-githu @irenefaith On the recent transactions summary section for both receiving and issuing drugs, it would be important to have the quantity indicated for easy identification and tracking of transactions. 

![image](https://user-images.githubusercontent.com/48719634/54668110-1c189600-4aff-11e9-8cf3-d78f9c4edc88.png)

**Comment by chris-githu** [comment]
@vogoti 
Please test this and confirm
