### ISSUE TITLE
Issue Drugs - Enter quantity specification 

### ISSUE THREAD

**Issue by Muchina-David** [chap-uzima/IQCare#23]
@chris-githu You added the functionality of specifications i.e. (packs) for tablets; (bottles) for liquids appearing at the part of Enter quantity when receiving. This is good in guiding the user. 
We need to add the same for issuing. As shown below, it does not appear for issuing transactions. 

![image](https://user-images.githubusercontent.com/48719634/54668606-533b7700-4b00-11e9-8f8b-9a76602ebdef.png)

**Comment by chris-githu** [comment]
@thnesh 
Please test this and confirm

**Comment by thnesh** [comment]
@chris-githu This has been effected/working.
