### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQCare#24]
![Capture](https://user-images.githubusercontent.com/31726479/54678924-30688d00-4b17-11e9-96cb-0cec28ca3837.JPG)
Some users are getting the attached error. Their passwords include numbers

**Comment by chris-githu** [comment]
I would need an example, preferably in Kiserian since I have the DB already to review.
@vogoti are you seeing this there?

**Comment by vogoti** [comment]
@chris-githu ,for Kiserian it is working fine

**Comment by mkaburu** [comment]
@victor please try and reset the password of one employee and use a mix of letters and numbers and see if you get the error as i upload Kikuyu DB

**Comment by vogoti** [comment]
@mkaburu I have tried and they can login successfully

**Comment by chris-githu** [comment]
@mkaburu Please see email.

**Comment by chris-githu** [comment]
Resolved
