### ISSUE TITLE
Patient Search Error

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQCare#26]
![mmm0](https://user-images.githubusercontent.com/31726479/54741591-00c98b80-4bd0-11e9-8f45-fc2c49244ec5.JPG)
Getting this error when i open patient 4577

**Comment by chris-githu** [comment]
@mkaburu @jkarigi 
Has this been resolved?

**Comment by mkaburu** [comment]
@chris-githu This has been resolved
