### ISSUE TITLE
Marira Migration Error

### ISSUE THREAD

**Issue by jkarigi** [chap-uzima/IQCare#27]
Hi @chris-githu when migrating Kijabe Marira DB am getting some SQL exception errors,pls see attachments,thanks.
After the migration all tests are successful
![image](https://user-images.githubusercontent.com/34024830/54741907-e7750f00-4bd0-11e9-9708-2f0c916f1ba1.png)
[MariraMigrationLog.txt](https://github.com/chap-uzima/IQCare/files/2991345/MariraMigrationLog.txt)
[Test MigrationLog.txt](https://github.com/chap-uzima/IQCare/files/2991347/Test.MigrationLog.txt)

**Comment by chris-githu** [comment]
@jkarigi Please send me this DB via email.

**Comment by chris-githu** [comment]
@jkarigi 
There are a good number of issues here.
Please do not go ahead with the migration at Marira until we resolve this

**Comment by jkarigi** [comment]
Hi Chris,
Did you manage to check Marira DB?

**Comment by jkarigi** [comment]
After Migrating in my machine with the latest Four2One,am getting the same error.

**Comment by chris-githu** [comment]
@jkarigi 
I have published an update to 421 that should resolve this issue.
Please test.
