### ISSUE TITLE
Kijabe Marira Migration Testing

### ISSUE THREAD

**Issue by jkarigi** [chap-uzima/IQCare#28]
@chris-githu when testing migration for Kijabe marira DB & choosing the IQCareV1 DB on the 421 App it is highlighted with a warning,Is it OK?
![image](https://user-images.githubusercontent.com/34024830/54742050-5488a480-4bd1-11e9-833e-ba3723040695.png)

**Comment by chris-githu** [comment]
@jkarigi 
I have fixed this in 421 update
