### ISSUE TITLE
Four2One App crash

### ISSUE THREAD

**Issue by thnesh** [chap-uzima/IQCare#32]
**The app is crashing when updating the table structure.**
![app crash](https://user-images.githubusercontent.com/31725448/36624633-a2bb3132-1922-11e8-9475-e3b2077c70a5.png)
**Also there are just 3 counties in the App.**
![county update](https://user-images.githubusercontent.com/31725448/36624642-b91aee40-1922-11e8-8444-9ccfb8b01857.png)

**Comment by chris-githu** [comment]
@thnesh Thanks.
Please update to 1.0.0.6 and try again.

**Comment by thnesh** [comment]
@chris-githu Getting the following errors, where are the errors being logged so i can attach it?
![app update](https://user-images.githubusercontent.com/31725448/36662707-5949946a-1af0-11e8-8827-1c07833c7a9d.jpg)

**Comment by mkaburu** [comment]
@chris-githu  this is the log for mater db
![sketch3](https://user-images.githubusercontent.com/31726479/36675224-780a8c78-1b19-11e8-9202-96043369a2bf.png)
![sketch4](https://user-images.githubusercontent.com/31726479/36675225-7842f13a-1b19-11e8-8bef-b19c9025554d.png)
![sketch5](https://user-images.githubusercontent.com/31726479/36675226-787f2b46-1b19-11e8-9479-b3e8cb01bec6.png)

**Comment by chris-githu** [comment]
I'll go ahead and close this issue as the reported problem *AppCrash* has been resolved.

Please see #33 for exporting the log.
