### ISSUE TITLE
Patient Clinic ID Constraint

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#32]
@chris-githu Patient Clinic ID has a constraint of 10 digits,requesting if it can be removed
![image](https://user-images.githubusercontent.com/31826771/54807218-9840e400-4c8d-11e9-9e8c-635a7cdc98a1.png)

**Comment by chris-githu** [comment]
@vogoti @snyachae 
Please confirm whether this has been resolved

**Comment by snyachae** [comment]
Having a challenge with my laptop, its back for repair, immediately I get it back I will be able to check on it.SilasOn Mar 26, 2019 09:28, Christopher Githu <notifications@github.com> wrote:@vogoti @snyachae
Please confirm whether this has been resolved

**Comment by vogoti** [comment]
@chris-githu This is resolved
