### ISSUE TITLE
Pill Balance

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#33]
@chris-githu @carolmaina @Muchina-David @mkaburu 
Kikuyu are requesting if a textbox for indicating pill balance can be included on the pharmacy form,what are your thoughts?

**Comment by carolmaina** [comment]
@vogoti It is important to have a text box indicating the pill balance

**Comment by chris-githu** [comment]
@carolmaina @vogoti 
From a usability perspective, why do we need this?
