### ISSUE TITLE
Export Log Feature

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#33]
Add capability to export migration log to a file.

@thnesh @mkaburu @vogoti

**Comment by chris-githu** [comment]
This, along with additional logging improvements, has been addressed in 5bbca46 v1.0.0.7

Please update and test.
P.S. The log file is saved to `C:\IQCare Migration\MigrationLog.txt`

**Comment by mkaburu** [comment]
@chris-githu Baraka log file
[MigrationLog.txt](https://github.com/chap-uzima/IQCare/files/1765761/MigrationLog.txt)

**Comment by thnesh** [comment]
@chris-githu Mutomo Migration file
[Mutomo MigrationLog.txt](https://github.com/chap-uzima/IQCare/files/1765833/Mutomo.MigrationLog.txt)

**Comment by chris-githu** [comment]
@thnesh, @mkaburu  Please test Mutomo & Baraka again. I have published v1.0.0.9.

I'll close this issue. Please open new tickets in case of additional errors.
