### ISSUE TITLE
Apostrophe in mst_Village causing Registration SP fail

### ISSUE THREAD

**Issue by thnesh** [chap-uzima/IQCare#35]
@chris-githu Mutomo Migration error for restrations as logged below
[MigrationLog.txt](https://github.com/chap-uzima/IQCare/files/1780955/MigrationLog.txt)

**Comment by chris-githu** [comment]
@thnesh This should be fixed in `v1.0.0.10`
Please test.

**Comment by thnesh** [comment]
@chris-githu the migration has completed successfully in the app. will be check if data in the tables aligns completely later.
