### ISSUE TITLE
Pharmacy Prescription - Remove and Re-enter drug

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQCare#37]
@chris-githu  When you remove a drug in a prescription form and try re-entering the same drug you get an error the drug already exists in the list
![pharcy error](https://user-images.githubusercontent.com/31726479/55088520-e9e9d400-50bc-11e9-9e36-6df0c19ef86f.JPG)

**Comment by mkaburu** [comment]
@chris-githu Keyboard number pad not working in pharmacy forms and pharmacy module

**Comment by chris-githu** [comment]
@mkaburu 
Remove and re-enter is ready for testing in 2.0.3. I'll need to recreate numpad issue so moving that out of this issue.

**Comment by chris-githu** [comment]
@mkaburu for testing

**Comment by mkaburu** [comment]
@chris-githu This is sorted. Of note if you go to the pharmacy form through encounter history you will end up with problems. But if you click on the pharmacy in the list of forms you can remove and re-add the drug

**Comment by chris-githu** [comment]
_if you go to the pharmacy form through encounter history you will end up with problems_

Please explain. I was able to edit a pharmacy form on the cloud server using this path

**Comment by mkaburu** [comment]
@chris-githu  sorry i tried on a form that was created earlier. i need to reboot now

**Comment by chris-githu** [comment]
@mkaburu Lol. I'll go ahead and close this.

**Comment by Muchina-David** [comment]
@chris-githu The issue about keyboard number pad not working, i think it was resolved for Pharmacy Module but still persists when typing the prescription in CCC Module. @mkaburu @vogoti have you experienced this too?
