### ISSUE TITLE
Kijabe Migration Error

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQCare#38]
@chris-githu kindly see the error log for Kijabe DB
[MigrationLog.txt](https://github.com/chap-uzima/IQCare/files/3014974/MigrationLog.txt)

**Comment by mkaburu** [comment]
![i](https://user-images.githubusercontent.com/31726479/55106511-37c40380-50e0-11e9-8601-05ea03b8d938.JPG)

**Comment by chris-githu** [comment]
@mkaburu 
I believe this was resolved. Please close
