### ISSUE TITLE
Regimens reseting even after successful migration

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#4]
Migrated sites are having the contents of ARVTreatmentTracker reset to one regimen after some time.

FYI @vogoti

**Comment by chris-githu** [comment]
FYI This is due to a bug in IQCare. I have reported this to HMIS but will be providing a fix.
FYI @vogoti @mkaburu

**Comment by mkaburu** [comment]
[Regimen.docx](https://github.com/chap-uzima/IQCare/files/2914856/Regimen.docx)

This is what i have found out so far after running the script
@chris-githu

**Comment by chris-githu** [comment]
@mkaburu 
Thanks for testing. Please plan to apply this fix tomorrow morning. 
I can assist with some of the sites if I get TV access. I'll send you the scripts via email.

Thanks.
