### ISSUE TITLE
St Teresa Migration error

### ISSUE THREAD

**Issue by pgitonga** [chap-uzima/IQCare#42]
Hello Chris,
Pls see the error am getting on migrating  St Teresa data.
The run tests are all ok.

![St Teresa Migration Error](https://user-images.githubusercontent.com/34089792/55236382-d9fafd00-5240-11e9-8e74-9893824fe1a7.PNG)

**Comment by chris-githu** [comment]
@pgitonga Your SQL Server is timing out before the completion of Pharmacy migration.
You might need to reindex your IQCare database **before** migrating

**Comment by chris-githu** [comment]
@pgitonga I believe this was resolved.
Please close
