### ISSUE TITLE
Kagio Migration error

### ISSUE THREAD

**Issue by pgitonga** [chap-uzima/IQCare#43]
Hello Chris,
Pls see the long error am getting on migrating Kagio DB.

![Kagio migration error1](https://user-images.githubusercontent.com/34089792/55238097-b9cd3d00-5244-11e9-810a-9339ef8ff440.PNG)
![Kagio Migration error cont2](https://user-images.githubusercontent.com/34089792/55238101-bb970080-5244-11e9-862d-a1142f498d01.PNG)
![Kagio Migration error cont](https://user-images.githubusercontent.com/34089792/55238103-bcc82d80-5244-11e9-9e2d-5e7392cf15ef.PNG)

**Comment by pgitonga** [comment]
Hello Chris on running tests on the same DB (Kagio) am getting the attached error.

[Kagio Test Log.txt](https://github.com/chap-uzima/IQCare/files/3022976/Kagio.Test.Log.txt)

**Comment by chris-githu** [comment]
Resolved
