### ISSUE TITLE
Gatithi Migration errors

### ISSUE THREAD

**Issue by pgitonga** [chap-uzima/IQCare#44]
Hello Chris,
Pls find attached migration and test logs for Gatithi and advice

Thanks

[Gatithi MigrationLog.txt](https://github.com/chap-uzima/IQCare/files/3023089/Gatithi.MigrationLog.txt)
[Gatithi TestLog.txt](https://github.com/chap-uzima/IQCare/files/3023090/Gatithi.TestLog.txt)

**Comment by chris-githu** [comment]
@pgitonga I believe this is resolved
