### ISSUE TITLE
Anti-TB Meds

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#49]
Add Anti-TB Meds
[IQCare - Anti-TB drugs.xlsx](https://github.com/chap-uzima/IQCare/files/3058421/IQCare.-.Anti-TB.drugs.xlsx)

**Comment by chris-githu** [comment]
@Muchina-David Please test this on the demo server

@vogoti @mkaburu

**Comment by Muchina-David** [comment]
@chris-githu I think this is okay. Thanks. 

@vogoti @mkaburu
