### ISSUE TITLE
Kanziku Viral Loads Not Migrated

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#5]
Looks like Kanziku had a custom lab test for VLs that was not migrated
FYI @mkaburu

**Comment by mkaburu** [comment]
![kan](https://user-images.githubusercontent.com/31726479/53542966-e4d34c80-3b31-11e9-99c3-373a5cc4c6c8.JPG)
This is the output after running the script

**Comment by chris-githu** [comment]
@mkaburu Is this accurate/similar to VLs before migration?

**Comment by mkaburu** [comment]
with V4VL as(
select
a.PatientPK
,a.DateOrdered
,a.DateReported
,a.VLResult
,a.StartARTDate
from IQToolsKanzikuV4.dbo.tmp_viralloads a)


 ,V5VL as(select
a.PatientPK
,a.DateOrdered
,a.DateReported
,a.VLResult
,a.StartARTDate
,b.Ptn_Pk
from IQTools.dbo.tmp_viralloads a
left join tmp_PatientMaster b on a.PatientPK=b.PatientPK
where a.DateReported <'20190101')
 

 ,linelist as(select 
a.PatientPK
,a.DateOrdered DateOrderedV$
,a.VLResult VLResultV4
,b.Ptn_Pk
,b.DateOrdered
,b.VLResult
,case when a.PatientPK<>b.Ptn_Pk then 1 else 0 end as DoesNotMatch
 from V4VL a
 left join V5VL b on a.PatientPK=b.Ptn_Pk)

 select* from linelist where DoesNotMatch=1

**Comment by mkaburu** [comment]
I used the above query and there is no VL that has not migrated

**Comment by chris-githu** [comment]
Great!
We can consider this resolved then. Please reopen if not.

Thanks.
