### ISSUE TITLE
Pharmacy Module: Stock Summary Export to File

### ISSUE THREAD

**Issue by Muchina-David** [chap-uzima/IQCare#51]
@chris-githu Is it possible to have an option to download the Stock Summary data as an Excel document?

**Comment by chris-githu** [comment]
@Muchina-David Yes
I'm adding functionality to export the table as an excel or pdf document.
Lookout for this in the next release

**Comment by Muchina-David** [comment]
@chris-githu Okay. Thanks

**Comment by chris-githu** [comment]
@Muchina-David Please test this on the demo server

@vogoti @mkaburu

**Comment by Muchina-David** [comment]
@chris-githu I have tested the Export to PDF, Excel and copy functions. This is a good addition. I have the following suggestions:

1. Could the exported file have a timestamp on top with date and time? This would help the user to know when the data was generated and to distinguish when they have more than one downloaded files. 

2. Could we do away with the repetitions on the downloaded file? I understand that they are appearing because of having multiple batches but it would be good to have them as they appear on the system itself. 

![image](https://user-images.githubusercontent.com/48719634/56133901-2317b480-5f96-11e9-8681-c290ad44f3f7.png)

**Comment by Muchina-David** [comment]
@chris-githu I have also thought of renaming the Quantity column in Stock summary as 'Quantity per batch' to help the user distinguish 'Quantity per batch' from 'Total'. 

![image](https://user-images.githubusercontent.com/48719634/56134366-1ba4db00-5f97-11e9-97e2-b3e1ca1826b0.png)

**Comment by chris-githu** [comment]
@Muchina-David Unfortunately the file export module does not support the column and row grouping that we've done with the table.
I'll do some more research to see what can be done in the future.
I'll rename the `quantity` title as suggested for the next release.
