### ISSUE TITLE
Pharmacy Queue number icon 

### ISSUE THREAD

**Issue by Muchina-David** [chap-uzima/IQCare#53]
@chris-githu Is it possible for the circular icon showing number of patients in the pharmacy queue to come to the front? Currently, it appears partly blocked as shown in the image below. 

![image](https://user-images.githubusercontent.com/48719634/55952830-2db70e80-5c63-11e9-9e3b-0a4e391657a1.png)

**Comment by chris-githu** [comment]
@Muchina-David This is largely due to your screen size/resolution. I will edit it to wrap correctly.
Thanks.

**Comment by chris-githu** [comment]
@Muchina-David Please test this on the demo server

@vogoti @mkaburu

**Comment by Muchina-David** [comment]
@chris-githu I have tested this. It's okay now. Thanks. 

![image](https://user-images.githubusercontent.com/48719634/56131518-50f9fa80-5f90-11e9-9bf3-e607dfa6973f.png)
