### ISSUE TITLE
Receiving/ Issuing Stocks Linkage

### ISSUE THREAD

**Issue by Muchina-David** [chap-uzima/IQCare#54]
@chris-githu I have observed the following issues using the Demo facility:

If you Issue equal quantities of drugs in a particular batch e.g. 25 packs in one transaction then another 25 packs; the process will complete but stock summary will indicate that the other quantity is still in the Main store. Also, the second issuing will not show in the "Recent transaction summary". 

If you Issue a batch more than once then the transactions under **Receive stocks** "Recent transaction summary" also increase equivalent to the number of times you issue the batch; yet you received it only once. @mkaburu You sorted this out in Kiserian. How did you go about it?

**Comment by chris-githu** [comment]
@Muchina-David 
I was able to replicate both these issues and will correct in v2.0.4

**Comment by chris-githu** [comment]
@Muchina-David 
Please test both these issues on the demo server

@vogoti @mkaburu

**Comment by Muchina-David** [comment]
@chris-githu Both issues have been resolved. Thanks. 

@vogoti @mkaburu
