### ISSUE TITLE
IQTools Refresh Error V4.0 DBs

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#57]
@chris-githu there is an error when refreshing some v4.0 DBs,please see attached Log
[IQTools Refresh Error V4.0.txt](https://github.com/chap-uzima/IQCare/files/3074092/IQTools.Refresh.Error.V4.0.txt)

**Comment by chris-githu** [comment]
@vogoti 
I thought you had already refreshed v4 DBs with the previous management console.

**Comment by chris-githu** [comment]
@vogoti 
This was resolved over the weekend.
Thanks.
