### ISSUE TITLE
Olkoroi HTS Error

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#6]
Hi Chris,am getting the attached error when trying to find client in HTS module for Olkoroi DB
![hts error](https://user-images.githubusercontent.com/31826771/53779387-f1c8b500-3f10-11e9-992d-07b8dcdf5226.png)

**Comment by chris-githu** [comment]
@mkaburu Please assist @vogoti with switching the IQCare 2.0 connection to local.

**Comment by vogoti** [comment]
@mkaburu @chris-githu ,resolved by using updated appsettings file
1.In the folder C:\inetpub\wwwroot\IQCareApi 
2.Change UseLocal to true (no quotes)
3.Change the connection string as appropriate. For Data Source make sure to use 2 back slashes.


{

"IQCareUri": 
"http://localhost/IQCare/",

"UseLocal": 
true,

"ConnectionStrings": {

"IQCareConnection": 
"Data Source=.\\sqlexpress;Initial Catalog=IQCare;Persist Security Info=True;User ID=sa;Password=c0nstella;MultipleActiveResultSets=True;Pooling=True"

}

}
