### ISSUE TITLE
Patient Names

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#67]
First Name
Middle Name
Last Name

No migration concerns. Migrate as is

**Comment by darkirui** [comment]
[names.txt](https://github.com/chap-uzima/IQCare/files/2369990/names.txt)

**Comment by darkirui** [comment]
[names.txt](https://github.com/chap-uzima/IQCare/files/2370020/names.txt)

**Comment by darkirui** [comment]
[names.txt](https://github.com/chap-uzima/IQCare/files/2370415/names.txt)

**Comment by darkirui** [comment]
[patientnames.txt](https://github.com/chap-uzima/IQCare/files/2374859/patientnames.txt)
Patient names ready for testing

**Comment by chris-githu** [comment]
Testing passed
