### ISSUE TITLE
Gender

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#68]
Male or Female

No concerns

**Comment by chris-githu** [comment]
Script to test DoBs
[DoB Testing.txt](https://github.com/chap-uzima/IQCare/files/2369673/DoB.Testing.txt)

**Comment by thnesh** [comment]
Script to test Gender
[Test Gender.txt](https://github.com/chap-uzima/IQCare/files/2369868/Test.Gender.txt)

Tested in Voi DB and all migrated

**Comment by thnesh** [comment]
Gender Test updated script for Count
[Test Gender Count.txt](https://github.com/chap-uzima/IQCare/files/2373674/Test.Gender.Count.txt)

**Comment by chris-githu** [comment]
Testing passed
