### ISSUE TITLE
Correction of Drug Expiry Date

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#68]
@chris-githu Wrong expiry Date was entered for AZT/3TC/NVP-300/150/200 Batch 72Z7959
Expiry should be 31/07/2019,pls assist

**Comment by chris-githu** [comment]
@vogoti 
You'd have to do this via script for now.
`UPDATE DrugBatch
SET ExpiryDate = CAST('_CorrectExpiryDate_' as datetime)
WHERE BatchNumber = '_CorrectBatchNumber_'`

**Comment by chris-githu** [comment]
@vogoti 
Was this resolved?

**Comment by vogoti** [comment]
@chris-githu Thanks,Resolved
