### ISSUE TITLE
Olkoroi Pharmacy Dispense

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#7]
@chris-githu When trying to dispense for the upgraded Olkoroi DB no drugs are loading

**Comment by chris-githu** [comment]
@vogoti How is pharmacy set up at Olkoroi? PM/SCM with same point dispense?

**Comment by vogoti** [comment]
@chris-githu ,resolved by disabling module links for Pharmacy


delete from lnk_FacilityModule where moduleId in (
select ModuleId from mst_module 
where ModuleName IN ('PM/SCM With Same point dispense','PM/SCM','Pharmacy Dispense'))
