### ISSUE TITLE
Drug List Not Loading

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#71]
Upgraded Githunguri to 2.0.4 but drugs are not loading on Receive Drugs window.Also getting attached errors when opening Pharmacy module and Receive Drugs Window.
![Error Pharmacy2](https://user-images.githubusercontent.com/31826771/56888102-ed85c780-6a7b-11e9-812d-8dc649fdccc8.PNG)

**Comment by chris-githu** [comment]
@vogoti Resolved?

**Comment by vogoti** [comment]
Resolved by Instaling V 2.0.2 IQCare Service:
https://healthintelcoke-my.sharepoint.com/:u:/g/personal/chris_healthintel_co_ke/EXC2ekH84EtDuyviDQO84EQB8ZSZPXkXHh1QEvhc5EafpA?e=NOMucS
