### ISSUE TITLE
CDRR Report

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#73]
@chris-githu The CDRR report is picking Opening Balances but Quantity Dispensed column is populating Zeroes.
See Naivasha 06052019 DB and April CDRR Report.[https://drive.google.com/open?id=15tSNeKlhtzC2midz3fFBEVZKfRZVmOc4](url)
[Naivasha - FCDRR_Report - 2019-04-30.xlsx](https://github.com/chap-uzima/IQCare/files/3181255/Naivasha.-.FCDRR_Report.-.2019-04-30.xlsx)

**Comment by chris-githu** [comment]
@vogoti 
I'll need someone to do some further investigation and provide more info on this.
What version of IQCare are they running?
Please remember `v2.0.4` is a requirement for Pharmacy reports to work.

**Comment by vogoti** [comment]
@chris-githu I upgraded Naivasha DB from 2.0.2 to 2.0.4 but the report is still not populating or should it populate Data captured after update to 2.0.4?

**Comment by chris-githu** [comment]
[Naivasha - FCDRR_Report - 2019-04-30.xlsx](https://github.com/chap-uzima/IQCare/files/3201327/Naivasha.-.FCDRR_Report.-.2019-04-30.xlsx)

@vogoti Seems fine to me. Is there a specific issue I should be seeing?

**Comment by vogoti** [comment]
@chris-githu It is Ok,thanks

@jkarigi lets get Naivasha to 2.0.4 and retest
