### ISSUE TITLE
Postal Address

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#77]
No concerns
Migrate as is

**Comment by vogoti** [comment]
Postal address testing script
[PhysicalAddress.txt](https://github.com/chap-uzima/IQCare/files/2370617/PhysicalAddress.txt)

**Comment by chris-githu** [comment]
[PhysicalAddress.txt](https://github.com/chap-uzima/IQCare/files/2370781/PhysicalAddress.txt)
With record counts

**Comment by chris-githu** [comment]
Testing passed
