### ISSUE TITLE
Dispensing window enhancement

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQCare#77]
@chris-githu 
Mater are requesting for two  enhancements in the dispensing window;

-  to show the clinician who did the prescription in case there is need for revision of the prescription.

- Patient vitals  especially weight  in case of dosage changes

**Comment by Muchina-David** [comment]
@mkaburu Thanks for this suggestion. This info is important for the pharmacist. We had identified a similar thing and logged it as issue #19 - _Additional information on the dispensing window._ 

I believe @chris-githu is working on it. 

@vogoti

**Comment by mkaburu** [comment]
@Muchina-David sorry i had not seen it. i will close the issue and refer to issue #19
