### ISSUE TITLE
Mobile Phone Number

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#78]
Concerns
Validation issues HMIS requires formatted phone number.
Migrate as is. Plan for DQA of phone numbers.

**Comment by Rugute** [comment]
Check Phone number alternating from where NULL is present.
[MobileNumber.txt](https://github.com/chap-uzima/IQCare/files/2370429/MobileNumber.txt)

**Comment by chris-githu** [comment]
[MobilePhoneNumber.txt](https://github.com/chap-uzima/IQCare/files/2370566/MobilePhoneNumber.txt)

**Comment by chris-githu** [comment]
Testing passed
