### ISSUE TITLE
IQTools V5.0.0.8 Error for Upgraded Sites

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#8]
@Chris,am getting the attached error when i try to use the online verison(5.0.0.8) for the upgraded Narok sites but the offline V5.0.0.9 works fine,please assist
![iqtools error](https://user-images.githubusercontent.com/31826771/53937168-59bbfe80-40bd-11e9-83de-d56e79592bd3.png)

**Comment by chris-githu** [comment]
@vogoti Published v5.0.0.9. Please update and confirm

**Comment by vogoti** [comment]
@chris-githu,its fine now thanks
