### ISSUE TITLE
Treatment supporter

### ISSUE THREAD

**Issue by mkaburu** [chap-uzima/IQCare#87]
@chris-githu  am getting the attached error when trying to update treatment supporter details
![c](https://user-images.githubusercontent.com/31726479/58503312-21463100-8191-11e9-9d55-ec00fada4ac2.JPG)

**Comment by chris-githu** [comment]
@mkaburu 
Is this still an issue in 2.0.5?

**Comment by mkaburu** [comment]
@chris-githu No its now working. in Ver 2.0.5

**Comment by chris-githu** [comment]
Resolved
