### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by chris-githu** [chap-uzima/IQCare#89]
Concerns
Between 34 and 40

**Comment by jkarigi** [comment]
[Temperature.txt](https://github.com/chap-uzima/IQCare/files/2371043/Temperature.txt)

**Comment by chris-githu** [comment]
[Temperature with SUM and COUNT.txt](https://github.com/chap-uzima/IQCare/files/2371088/Temperature.with.SUM.and.COUNT.txt)

**Comment by chris-githu** [comment]
Testing passed
