### ISSUE TITLE
Re enrollment Not Possible-Updated Sites

### ISSUE THREAD

**Issue by vogoti** [chap-uzima/IQCare#9]
@chris-githu Its not possible to reenroll a care ended patient
![reenrolment error](https://user-images.githubusercontent.com/31826771/53941658-c0471980-40c9-11e9-88c7-36318f1849fe.png)

**Comment by chris-githu** [comment]
@vogoti Noted. Working on it

**Comment by chris-githu** [comment]
@vogoti I've fixed this on the cloud server.
Please confirm that it works as expected and I'll send you the fix via email.

**Comment by chris-githu** [comment]
Resolved
